version: '3'

services:
  db:
    image: mysql:latest
    container_name: db
    ports:
      - 3307:3306
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=biblioteca
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user  

  django:
    build:
      context: .
      dockerfile: Dockerfile.django
    container_name: django
    ports:
      - 8000:8000
    volumes:
      - .:/app
      - ./docker/supervisor:/etc/supervisor/conf.d
      - static:/app/static
      - media:/app/media
    command: ["sh", "-c", "python manage.py migrate && python manage.py collectstatic --noinput && supervisord -n"]
    depends_on:
      - db
      
  web:
    image: nginx:latest
    container_name: web
    volumes:
      - ./docker/nginx/templates:/etc/nginx/templates
      - static:/app/static
      - media:/app/media
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    depends_on:
      - django

volumes:
  mysql_data:
  static:
  media:
